### ISSUE TITLE
Cannot resolve vue-i18n on pnpm! please install it on 'node_modules'

### ISSUE THREAD

**Issue by mohammad-salehealizadegan** [sfxcode/nuxt3-primevue-starter#32]
**### After run pnpm install i got the below error so i run pnpm add vue-i18 but i got the below code again when i run pnpm dev:**

[9:00:06 PM]  ERROR  Cannot start nuxt:  Cannot resolve vue-i18n on pnpm! please install it on 'node_modules'
                                                                    9:00:05 PM
  at tryResolve (node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.11_vue@3.3.4/node_modules/@nuxtjs/i18n/dist/module.mjs:136:9)
  at async setupAlias (node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.11_vue@3.3.4/node_modules/@nuxtjs/i18n/dist/module.mjs:341:38)
  at async setup (node_modules/.pnpm/@nuxtjs+i18n@8.0.0-beta.11_vue@3.3.4/node_modules/@nuxtjs/i18n/dist/module.mjs:1573:5)
  at async normalizedModule (node_modules/.pnpm/@nuxt+kit@3.5.3/node_modules/@nuxt/kit/dist/index.mjs:2137:17)
  at async installModule (node_modules/.pnpm/@nuxt+kit@3.5.3/node_modules/@nuxt/kit/dist/index.mjs:2407:95)
  at async initNuxt (node_modules/.pnpm/nuxt@3.5.3_@types+node@20.3.1_eslint@8.43.0_sass@1.63.4_typescript@5.1.3/node_modules/nuxt/dist/index.mjs:2928:7)
  at async load (node_modules/.pnpm/nuxi@3.5.3/node_modules/nuxi/dist/chunks/dev.mjs:204:9)
  at async Object.invoke (node_modules/.pnpm/nuxi@3.5.3/node_modules/nuxi/dist/chunks/dev.mjs:248:5)
  at async _main (node_modules/.pnpm/nuxi@3.5.3/node_modules/nuxi/dist/cli.mjs:48:20)

**Comment by sfxcode** [comment]
Hi, cleaned project and tested without errors. Not needed to add vue-i18 in my case.

Maybe you can share your environment by:
```
nuxi info
```

My current setup:

------------------------------
- Operating System: Darwin
- Node Version:     v18.15.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.6.1
- Builder:          vite
- User Config:      devtools, ssr, runtimeConfig, modules, content, i18n, unocss, primevue, css, pinia, build, sourcemap
- Runtime Modules:  @formkit/nuxt@0.17.3, @sfxcode/nuxt-primevue@1.2.2, @unocss/nuxt@0.53.1, @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-beta.11, @nuxt/content@2.7.0, @vueuse/nuxt@10.2.0
- Build Modules:    -
------------------------------


Greetings, Tom

**Comment by mohammad-salehealizadegan** [comment]
------------------------------
- Operating System: Darwin
- Node Version:     v18.13.0
- Nuxt Version:     3.5.3
- Nitro Version:    2.4.1
- Package Manager:  pnpm@8.1.1
- Builder:          vite
- User Config:      devtools, ssr, runtimeConfig, modules, content, i18n, unocss, primevue, css, pinia, build, sourcemap
- Runtime Modules:  @formkit/nuxt@0.17.3, @sfxcode/nuxt-primevue@1.2.2, @unocss/nuxt@0.53.1, @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-beta.11, @nuxt/content@2.7.0, @vueuse/nuxt@10.2.0
- Build Modules:    -

**Comment by mohammad-salehealizadegan** [comment]
Actually i install this project now and it’s so clean without any additional or customization

**Comment by mohammad-salehealizadegan** [comment]
> Hi, cleaned project and tested without errors. Not needed to add vue-i18 in my case.
> 
> Maybe you can share your environment by:
> 
> ```
> nuxi info
> ```
> 
> My current setup:
> 
> * Operating System: Darwin
> * Node Version:     v18.15.0
> * Nuxt Version:     3.5.3
> * Nitro Version:    2.4.1
> * Package Manager:  pnpm@8.6.1
> * Builder:          vite
> * User Config:      devtools, ssr, runtimeConfig, modules, content, i18n, unocss, primevue, css, pinia, build, sourcemap
> * Runtime Modules:  @formkit/nuxt@0.17.3, @sfxcode/nuxt-primevue@1.2.2, @unocss/nuxt@0.53.1, @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-beta.11, @nuxt/content@2.7.0, @vueuse/nuxt@10.2.0
> * Build Modules:    -
> 
> Greetings, Tom

thank you for your replay
here you are:

Operating System: Darwin
Node Version: v18.13.0
Nuxt Version: 3.5.3
Nitro Version: 2.4.1
Package Manager: pnpm@8.1.1
Builder: vite
User Config: devtools, ssr, runtimeConfig, modules, content, i18n, unocss, primevue, css, pinia, build, sourcemap
Runtime Modules: @formkit/nuxt@0.17.3, @sfxcode/nuxt-primevue@1.2.2, @unocss/nuxt@0.53.1, @pinia/nuxt@0.4.11, @nuxtjs/i18n@8.0.0-beta.11, @nuxt/content@2.7.0, @vueuse/nuxt@10.2.0
Build Modules: -


Actually i install this project now and it’s so clean without any additional or customization

**Comment by sfxcode** [comment]
should work like expected
